In [24]:
# 평균값

# 모든 열의 평균 값 : DataFrame객체.mean()
# 특정 열의 평균 값 : DataFreme객체["열 이름"].mean() / Series

import pandas as pd

In [25]:
df = pd.read_csv("./data/auto-mpg.csv", header=None)

df.columns = [
    "mpg", "cylinders", "displacement", "horsepower", "weight", "acceletation", "model year", "origin", "name"
]

df.head()

,mpg,cylinders,displacement,horsepower,weight,acceletation,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    str
 4   weight        398 non-null    float64
 5   acceletation  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

In [27]:
df.mean(numeric_only=True)

mpg               23.514573
cylinders          5.454774
displacement     193.425879
weight          2970.424623
acceletation      15.568090
model year        76.010050
origin             1.572864
dtype: float64

In [28]:
df["mpg"].mean().round(2)

np.float64(23.51)

In [29]:
round(df["mpg"].mean(), 1)

np.float64(23.5)

In [30]:
# 중앙값
# 모든 열의 중앙 값 : DataFrame객체.median()
# 특정 열의 중앙 값 : DataFrame객체["열 이름"].median()

print(df.median(numeric_only=True))
print(df.mpg.median())

mpg               23.0
cylinders          4.0
displacement     148.5
weight          2803.5
acceletation      15.5
model year        76.0
origin             1.0
dtype: float64
23.0

In [31]:
df.max()

mpg                         46.6
cylinders                      8
displacement               455.0
horsepower                     ?
weight                    5140.0
acceletation                24.8
model year                    82
origin                         3
name            vw rabbit custom
dtype: object

In [32]:
print(df.max(numeric_only=True))
df["horsepower"]

mpg               46.6
cylinders          8.0
displacement     455.0
weight          5140.0
acceletation      24.8
model year        82.0
origin             3.0
dtype: float64

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...
393    86.00
394    52.00
395    84.00
396    79.00
397    82.00
Name: horsepower, Length: 398, dtype: str

In [33]:
df.min(numeric_only=True)

mpg                9.0
cylinders          3.0
displacement      68.0
weight          1613.0
acceletation       8.0
model year        70.0
origin             1.0
dtype: float64

In [37]:
print(df.std(numeric_only=True))

mpg               7.815984
cylinders         1.701004
displacement    104.269838
weight          846.841774
acceletation      2.757689
model year        3.697627
origin            0.802055
dtype: float64

In [38]:
# 상관계수
# DataFrame객체.corr()
# DataFrame객체[열 이름 리스트].corr()

df[["mpg", "weight"]].corr()

             mpg    weight
mpg     1.000000 -0.831741
weight -0.831741  1.000000