In [7]:
# CSV 파일로 저장
# 객체.to_csv("파일 이름(경로)")

import pandas as pd

data = {
    'name' : [ 'Jerry', 'Riah', 'Paul'],
    'algol' : [ "A", "A+", "B"],
    'basic' : [ "C", "B", "B+"],
    'c++' : [ "B+", "C", "C+"],
}

df = pd.DataFrame(data)
df = df.set_index('name')

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [6]:
df.to_csv("./data/df_sample.csv")

In [8]:
df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [9]:
df.to_csv("./data/df_sample_no_index.csv", index=False)

In [ ]:
# JSON 파일로 저장
# DataFrame 객체.to_json("파일이름(경로)")

import pandas as pd

data = {
    'name' : [ 'Jerry', 'Riah', 'Paul'],
    'algol' : [ "A", "A+", "B"],
    'basic' : [ "C", "B", "B+"],
    'c++' : [ "B+", "C", "C+"],
}

df = pd.DataFrame(data)
df = df.set_index('name')

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [11]:
df.to_json("./data/df_sample.json")

In [12]:
df.to_json("./data/df_sample_split.json", orient="split")

In [ ]:
df.to_json("./data/df_sample_records.json", orient="records")

In [14]:
df.to_json("./data/df_sample_index.json", orient="index")

In [15]:
df.to_json("./data/df_sample_columns.json", orient="columns")

In [16]:
df.to_json("./data/df_sample_values.json", orient="values")