In [1]:
import pandas as pd

In [2]:
fruit_names = pd.Series(["Apple", "Banana", "Cherry"])
fruit_names

0     Apple
1    Banana
2    Cherry
dtype: str

In [3]:
pd.Series(["Apple", "Banana", "Cherry"], dtype = "string")

0     Apple
1    Banana
2    Cherry
dtype: string

In [4]:
pd.Series(["Apple", "Banana", "Cherry"], dtype=pd.StringDtype())

0     Apple
1    Banana
2    Cherry
dtype: string

In [5]:
fruit_names.astype("string")

0     Apple
1    Banana
2    Cherry
dtype: string

In [6]:
# 문자열 메서드
# 문자열 매서드 적용(lower):Series 객체.str.lower() or Index 객체.str.lower()

import pandas as pd
import numpy as np

ser = pd.Series([
    "Apple_사과",
    "Banana_바나나",
    "Cherry_체리",
    np.nan],
    index=["First ", " Second", " Third", "Forth"])

ser2 = pd.Series([
    "Apple_사과",
    "Banana_바나나",
    "Cherry_체리",
    np.nan],
    index=["First ", " Second", " Third", "Forth"], dtype="string")

In [7]:
print(ser.str.lower())
print(ser.str.upper())
print(ser.str.len())

First        apple_사과
 Second    banana_바나나
 Third      cherry_체리
Forth             NaN
dtype: str
First        APPLE_사과
 Second    BANANA_바나나
 Third      CHERRY_체리
Forth             NaN
dtype: str
First       8.0
 Second    10.0
 Third      9.0
Forth       NaN
dtype: float64

In [8]:
ser

First        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Forth             NaN
dtype: str

In [9]:
result1 = ser.str.split("_")
result1

First        [Apple, 사과]
 Second    [Banana, 바나나]
 Third      [Cherry, 체리]
Forth                NaN
dtype: object

In [10]:
result2 = ser.str.split("_", expand=True)
result2

              0    1
First     Apple   사과
 Second  Banana  바나나
 Third   Cherry   체리
Forth       NaN  NaN

In [11]:
ser.str.split("_").str.get(0)

First       Apple
 Second    Banana
 Third     Cherry
Forth         NaN
dtype: object

In [12]:
# 문자열 메서드

idx = ser.index

print(idx)
print(idx.str.strip())

Index(['First ', ' Second', ' Third', 'Forth'], dtype='str')
Index(['First', 'Second', 'Third', 'Forth'], dtype='str')

In [13]:
print(ser.str.replace("_", ":", regex=False))

First        Apple:사과
 Second    Banana:바나나
 Third      Cherry:체리
Forth             NaN
dtype: str

In [14]:
print(ser.str.replace("[^a-zA-Z\s]", "", regex=True))

First       Apple
 Second    Banana
 Third     Cherry
Forth         NaN
dtype: str

<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\KDT-17\AppData\Local\Temp\ipykernel_18784\88319545.py:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  print(ser.str.replace("[^a-zA-Z\s]", "", regex=True))

In [15]:
print(ser.str[0])

First        A
 Second      B
 Third       C
Forth      NaN
dtype: str

In [16]:
print(ser.str[0:4])

First      Appl
 Second    Bana
 Third     Cher
Forth       NaN
dtype: str

In [17]:
ser.str.contains("A", na=False)

First       True
 Second    False
 Third     False
Forth      False
dtype: bool

In [20]:
ser.str.contains(r"[A|B][a-z]*")

First       True
 Second     True
 Third     False
Forth      False
dtype: bool

In [21]:
ser.str.fullmatch(r"[A|B][a-z]*")

First      False
 Second    False
 Third     False
Forth      False
dtype: bool

In [22]:
ser3 = pd.Series(["a1", "b2", "c3", "d4a5", "e6e7", "f8"], dtype="string")
print(ser3)

0      a1
1      b2
2      c3
3    d4a5
4    e6e7
5      f8
dtype: string

In [26]:
print(ser3.str.extractall(r"(\d)"))

print(ser3.str.extractall(r"(\d)").groupby(level=0).agg("".join))

         0
  match
0 0      1
1 0      2
2 0      3
3 0      4
  1      5
4 0      6
  1      7
5 0      8
    0
0   1
1   2
2   3
3  45
4  67
5   8

In [27]:
ser3.str.extractall(r"([a-z])").groupby(level=0).agg("".join)

    0
0   a
1   b
2   c
3  da
4  ee
5   f

In [28]:
#숫자를 별도의 컬럼으로 분리
ser3.str.extract(r"(?P<Letter>[a-z]+)(?P<Digit>\d+)")

  Letter Digit
0      a     1
1      b     2
2      c     3
3      d     4
4      e     6
5      f     8